// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ22E8bUJhzQDJ4hCVq6n0XDDZt6frrng',
    appId: '1:368330592345:web:e3701a940e3290c8516148',
    messagingSenderId: '368330592345',
    projectId: 'grampanchayat-527de',
    authDomain: 'grampanchayat-527de.firebaseapp.com',
    databaseURL: 'https://grampanchayat-527de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grampanchayat-527de.appspot.com',
    measurementId: 'G-JPDP7BMMEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDueo6tJBCqHYGKvqf_yHklPZKWDDo_xXc',
    appId: '1:368330592345:android:a07ed2f1b2174714516148',
    messagingSenderId: '368330592345',
    projectId: 'grampanchayat-527de',
    databaseURL: 'https://grampanchayat-527de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grampanchayat-527de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKo_LKxBW2M5bR7Yj5rqyeAdTrHZh1ns',
    appId: '1:368330592345:ios:3d507bba88c49833516148',
    messagingSenderId: '368330592345',
    projectId: 'grampanchayat-527de',
    databaseURL: 'https://grampanchayat-527de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grampanchayat-527de.appspot.com',
    iosBundleId: 'com.example.grampanchayat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKo_LKxBW2M5bR7Yj5rqyeAdTrHZh1ns',
    appId: '1:368330592345:ios:3d507bba88c49833516148',
    messagingSenderId: '368330592345',
    projectId: 'grampanchayat-527de',
    databaseURL: 'https://grampanchayat-527de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grampanchayat-527de.appspot.com',
    iosBundleId: 'com.example.grampanchayat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ22E8bUJhzQDJ4hCVq6n0XDDZt6frrng',
    appId: '1:368330592345:web:07dbd3c638db642e516148',
    messagingSenderId: '368330592345',
    projectId: 'grampanchayat-527de',
    authDomain: 'grampanchayat-527de.firebaseapp.com',
    databaseURL: 'https://grampanchayat-527de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grampanchayat-527de.appspot.com',
    measurementId: 'G-Z6TM4PRDX9',
  );
}
